check50:
  dependencies:
    - "jupyter>=1.0"
    - "pandas>=1.0"
    - "nbformat>=5"
    - "matplotlib>=3.2"
    - "scipy>=1.4"
    - "nbconvert<=5.5.0"
  files:
    - !exclude "*"
    - !require "module1.ipynb"
